create table public.core_change_proposals (
 id bigint generated by default as identity primary key,
 profile text not null, node_key text not null, source_job_id bigint references public.os_jobs(id),
 source_event_id bigint references public.os_events(id), before_data jsonb, proposed_data jsonb not null,
 status text not null default 'pending' check(status in ('pending','accepted','rejected','superseded')),
 reviewed_by text, reviewed_at timestamptz, created_at timestamptz not null default now()
);
alter table public.core_change_proposals enable row level security;
revoke all on public.core_change_proposals from public,anon,authenticated;
grant select,insert,update on public.core_change_proposals to service_role;
grant usage,select on sequence public.core_change_proposals_id_seq to service_role;

create function public.review_core_change(p_id bigint,p_profile text,p_decision text)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare p public.core_change_proposals; current_row jsonb; new_id bigint; row_data jsonb; cols text; vals text; sets text;
begin
 if p_decision not in ('accepted','rejected') then raise exception 'Invalid decision'; end if;
 perform pg_advisory_xact_lock(hashtextextended('core-review:'||p_profile,0));
 select * into p from public.core_change_proposals where id=p_id and profile=p_profile for update;
 if not found then raise exception 'Proposal not found'; end if;
 if p.status <> 'pending' then return jsonb_build_object('status',p.status,'replayed',true); end if;
 if p_decision='accepted' then
   select to_jsonb(n) into current_row from public.core_nodes n where profile=p_profile and node_key=p.node_key and status='active' for update;
   if current_row is distinct from p.before_data then
     update public.core_change_proposals set status='superseded',reviewed_at=now(),reviewed_by='nadine' where id=p_id;
     return jsonb_build_object('status','superseded');
   end if;
   row_data := p.proposed_data || jsonb_build_object('profile',p_profile,'node_key',p.node_key,'author','system','updated_at',now());
   row_data := jsonb_set(row_data,'{metadata}',coalesce(row_data->'metadata','{}')||jsonb_build_object('approved_by','nadine','proposal_id',p_id));
   select string_agg(format('%I',key),','),string_agg(format('v.%I',key),','),string_agg(format('%I=v.%I',key,key),',') into cols,vals,sets from jsonb_object_keys(row_data) key;
   if current_row is null then
     execute format('insert into public.core_nodes (%s) select %s from jsonb_populate_record(null::public.core_nodes,$1) v returning id',cols,vals) into new_id using row_data;
   else
     execute format('update public.core_nodes set %s from jsonb_populate_record(null::public.core_nodes,$1) v where core_nodes.id=$2 returning core_nodes.id',sets) into new_id using row_data,(current_row->>'id')::bigint;
   end if;
 end if;
 update public.core_change_proposals set status=p_decision,reviewed_at=now(),reviewed_by='nadine' where id=p_id;
 return jsonb_build_object('status',p_decision,'node_id',new_id);
end $$;
revoke all on function public.review_core_change(bigint,text,text) from public,anon,authenticated;
grant execute on function public.review_core_change(bigint,text,text) to service_role;
